on:
  schedule:
    - cron: "0 0 * * *" # executa uma vez por dia
  workflow_dispatch:

jobs:
  build:
    name: Gerar animação da cobrinha
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: OtavioValeDev
          outputs: |
            dist/cobrinha.svg
            dist/cobrinha-dark.svg?palette=github-dark

      - name: Publicar animação na branch "output"
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
